# launch gnome-terminal by:
# export $(dbus-launch)
# gnome-terminal
- hosts: all
  tasks:
    - name: x11-apps
      shell: |
        sudo sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list
        sudo apt update
        sudo apt install -y xauth x11-apps dbus-x11 gnome-terminal
