all:
  children:
    target:
      hosts:
        vagrant:
          ansible_host: localhost
          ansible_user: vagrant
          ansible_port: 2022
          ansible_ssh_private_key_file: "{{ lookup('env','PWD') }}/.vagrant/machines/default/virtualbox/private_key"
  vars:
    ansible_python_interpreter: /usr/bin/python3
