- hosts: all
  tasks:
    - name: vscode
      shell: |
        sudo sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list
        sudo apt update
        sudo apt install -y xauth dbus-x11 x11-apps
        sudo dpkg -i /vagrant/code_1.47.3-1595520028_amd64.deb || true
        sudo apt install -y -f
        sudo apt install -y libx11-xcb1 libasound2
