- name: Setup for personal settings.
  block:
    - name: update
      apt:
        update_cache: yes
      become: yes

    - name: install personal preference packages
      apt:
        name: "{{ item.name }}"
        state: '{{ item.state | default("present") }}'
        purge: yes

      with_items:
        - name: zsh
        - name: git
      become: yes
      become_user: root

    - name: Change default shell to zsh
      shell: chsh -s $(which zsh) "{{ansible_ssh_user}}"
      become: yes
      become_user: root

    - name: dotfiles
      shell: |
        git clone https://github.com/chenhan1218/dotfiles
        ./dotfiles/deploy.sh
